services:
  db:
    image: postgres:15
    container_name: projeto_pg
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - projeto-network

  pgadmin:
    image: dpage/pgadmin4:7
    container_name: projeto_pgadmin
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - projeto-network
  api:
    build: ./backend      
    container_name: projeto_api
    restart: unless-stopped
    ports:
      - "4000:4000"        
    env_file: ./.env       
    environment:
      - DB_HOST=db         
      - PORT=4000
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
    depends_on:
      - db                 
    networks:
      - projeto-network    

volumes:
  postgres_data:
  pgadmin_data:

networks:
  projeto-network:
    driver: bridge